# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'rez_sphinx'
copyright = '2022, '
author = ''


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/3/': None}


# -- rez-sphinx start --
# -- DO NOT TOUCH --
#
# These lines are needed for rez-sphinx to work
#
from rez_sphinx import api

locals().update(api.bootstrap(locals()))
#
# If you want to add extra user customizations, please feel free to add any
# of them BELOW this line.
#
# -- rez-sphinx end --

import textwrap

rst_epilog = textwrap.dedent(
    """\
    .. _Sphinx conf.py: https://www.sphinx-doc.org/en/master/usage/configuration.html
    .. _Sphinx: https://www.sphinx-doc.org/en/master
    .. _`rez-depends`: https://github.com/nerdvegas/rez/wiki/Command-Line-Tools#rez-depends
    .. _`yaml`: https://pyyaml.org/wiki/PyYAMLDocumentation
    .. _build_requires: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#build_requires
    .. _early(): https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#early-binding-functions
    .. _help: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#help
    .. _index.rst: https://sphinx-tutorial.readthedocs.io/step-1
    .. _intersphinx: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
    .. _intersphinx_mapping: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
    .. _late(): https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#late-binding-functions
    .. _modules.rst: https://stackoverflow.com/questions/62822605/sphinx-modules-rst-warning-document-isnt-included-in-any-toctree
    .. _objects.inv: https://sphobjinv.readthedocs.io/en/latest/syntax.html
    .. _package help: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#help
    .. _package.py: https://github.com/nerdvegas/rez/wiki/Package-Commands
    .. _package_preprocess_function: https://github.com/nerdvegas/rez/wiki/Configuring-Rez#package_preprocess_function
    .. _private_build_requires: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#private_build_requires
    .. _requires: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#requires
    .. _rez help attribute: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#help
    .. _rez tests attribute: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#tests
    .. _rez-build: https://github.com/nerdvegas/rez/wiki/Getting-Started#building-your-first-package
    .. _rez-config: https://github.com/nerdvegas/rez/wiki/Command-Line-Tools#rez-config
    .. _sphinx-apidoc: https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html
    .. _sphinx-build: https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build
    .. _sphinx-quickstart: https://www.sphinx-doc.org/en/master/man/sphinx-quickstart.html
    .. _sphinx-rtd-theme: https://pypi.org/project/sphinx-rtd-theme/
    .. _sphinx.ext.autodoc: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
    .. _sphinx.ext.intersphinx: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
    .. _sphinx.ext.viewcode: https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html
    .. _toctree: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
    .. _variants: https://github.com/nerdvegas/rez/wiki/Package-Definition-Guide#variants
    """
)


# `readthedocs.io`_
# `sphinx theme`_
# `sphinx-rtd-theme`_
# https://sphinx-themes.org/
# https://sphinx-rtd-theme.readthedocs.io/en/stable/

# `rezconfig.py`_

# TODO : Consider remove rez-config references

# :ref:`rez_sphinx apidoc templates`

# TODO : Add these
# - build_documentation_key` - The rez_sphinx key information
# - :ref:`minimal bootstrapper`
